apiVersion: apps/v1 
kind: Deployment
metadata:
  name: socios
  labels: 
     app: socios

spec:
  replicas: 1 
  selector:
    matchLabels:
      app: socios

  template:
    metadata:
      labels:
        app: socios
    spec:
      containers:
      - name: socios
        image: DOCKER_IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 5003
        env:
        - name: AWS_ACCESS_KEY_ID
          value: ENV1
        - name: AWS_SECRET_ACCESS_KEY
          value: ENV2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
