apiVersion: v1
kind: Service
metadata:
  name: socios
  labels:
    app: socios
spec:
  selector:
    app: socios
  ports:
    - port: 80
      targetPort: 5003

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: socios-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: a30e8ad80d7ce496f87c317e39919031-393841883.us-east-1.elb.amazonaws.com
      http:
        paths:
          - path: /socios
            pathType: Prefix
            backend:
              service:
                name: socios
                port:
                  number: 80
